substitutions:
  device: lum-iot40
  comment: display TFT 2.4

esphome:
  name: lum-iot40fb
  comment: switchplate test yaml


esp32:
  board: firebeetle32

logger:
  level: verbose

color:
  - id: my_light_red
    red: 100%
  - id: my_black
    blue: 0%
    green: 0%
    red: 0%
  - id: my_red
    red: 100%
  - id: color_blue
    blue: 86%

spi:
  mosi_pin: 23
  miso_pin: 19
  clk_pin: 18

display:
  - id: my_display
    platform: ili9xxx
    model: TFT 2.4
    cs_pin: 5
    dc_pin: 16
    auto_clear_enabled: false
    data_rate: 40MHz
    dimensions: 320x240
    update_interval: never
    transform:
      mirror_y: false
      mirror_x: false
      swap_xy: true


touchscreen:
  - platform: xpt2046
    display: my_display
    id: my_toucher
    cs_pin: 14
    #irq_pin: 16
    setup_priority: -100
    update_interval: 50ms
    threshold: 300
    calibration:
      x_min: 340
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:
      mirror_x: false
      mirror_y: true
      swap_xy: true