---
esphome:
  name: m5stack-atom-echo

esp32:
  board: m5stack-atom


light:
  - platform: esp32_rmt_led_strip
    id: led
    name: None
    disabled_by_default: true
    entity_category: config
    pin: GPIO27
    default_transition_length: 0s
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    rmt_channel: 0
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button
    disabled_by_default: true
    entity_category: diagnostic
    id: button
    on_press:
      - status.push:
          trigger_id: custom_status
    on_release:
      - status.pop:
          trigger_id: custom_status
    on_click:
    - min_length: 50ms
      max_length: 350ms
      then:
        - status.push:
            trigger_id: custom_status
    - min_length: 500ms
      max_length: 1000ms
      then:
        - status.pop:
            trigger_id: custom_status


status_indicator:
  on_clear_all: #Manditory
    - light.turn_off:
        id: led

  on_app_error:
    then:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
        effect: Fast Pulse

  on_app_warning:
    then:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
        effect: None

  on_custom_status:
    - trigger_id: custom_status
      then:
        - light.turn_on:
            id: led
            red: 0%
            green: 100%
            blue: 0%
            brightness: 100%
            effect: None
    - trigger_id: custom_status2
      then:
        - light.turn_on:
            id: led
            red: 0%
            green: 100%
            blue: 50%
            brightness: 100%
            effect: None
