substitutions:
  name: test-xpt2046
  comment: test-xpt2046
  project_version: "1"

esphome:
  name: ${name}
  comment: "${name} - ${comment}"
  friendly_name: "${comment}"

  project:
    name: ${name}.${comment}
    version: ${project_version}

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

logger:
  level: verbose
  # hardware_uart: USB_CDC

psram:

spi:
  clk_pin: 7
  mosi_pin: 11
  miso_pin: 9

display:
  - platform: display_driver
    id: my_display
    model: ili9341
#    cs_pin: 5
    dc_pin: 12
    reset_pin: 35
    auto_clear_enabled: false
#    data_rate: 40MHz
    dimensions: 320x240
    update_interval: never
    transform:
      mirror_y: false
      mirror_x: false
      swap_xy: true



  # Define a PWM output on the ESP32
output:
  - platform: ledc
    pin: 16
    id: gpio_17_backlight_pwm

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: gpio_17_backlight_pwm
    name: Backlight
    id: back_light
    restore_mode: ALWAYS_ON
